# coding: utf-8

"""
    Watch List Screening API

    The Watch List Screening API provides an OFAC score value used for evaluation on how closely an individual's name, city, and country input fields match against entries on the OFAC SDN lists.  The Watch List Screening API also provides an OFAC status value which represents how VisaNet would process the individual's information if used in a cross-border OCT transaction.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WatchlistinquirypostResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, status=None, ofac_score=None, reference_number=None):
        """
        WatchlistinquirypostResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'status': 'str',
            'ofac_score': 'str',
            'reference_number': 'str'
        }

        self.attribute_map = {
            'status': 'status',
            'ofac_score': 'ofacScore',
            'reference_number': 'referenceNumber'
        }

        self._status = status
        self._ofac_score = ofac_score
        self._reference_number = reference_number

    @property
    def status(self):
        """
        Gets the status of this WatchlistinquirypostResponse.
        The Status value indicates if the OFAC Score exceeded or equaled the OFAC threshold or was less than the OFAC threshold.

        :return: The status of this WatchlistinquirypostResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this WatchlistinquirypostResponse.
        The Status value indicates if the OFAC Score exceeded or equaled the OFAC threshold or was less than the OFAC threshold.

        :param status: The status of this WatchlistinquirypostResponse.
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status

    @property
    def ofac_score(self):
        """
        Gets the ofac_score of this WatchlistinquirypostResponse.
        Note: The ofacScore value indicates the likelihood of an actual match of the individual’s information contained in the WLM request message against the OFAC SDN lists. The score range is 0 to 100.

        :return: The ofac_score of this WatchlistinquirypostResponse.
        :rtype: str
        """
        return self._ofac_score

    @ofac_score.setter
    def ofac_score(self, ofac_score):
        """
        Sets the ofac_score of this WatchlistinquirypostResponse.
        Note: The ofacScore value indicates the likelihood of an actual match of the individual’s information contained in the WLM request message against the OFAC SDN lists. The score range is 0 to 100.

        :param ofac_score: The ofac_score of this WatchlistinquirypostResponse.
        :type: str
        """
        if ofac_score is None:
            raise ValueError("Invalid value for `ofac_score`, must not be `None`")

        self._ofac_score = ofac_score

    @property
    def reference_number(self):
        """
        Gets the reference_number of this WatchlistinquirypostResponse.
        Note: The ReferenceNumber is a unique value set by the invoker used to tie together service calls related to a single OFAC transaction between the invoker and the WLM API.

        :return: The reference_number of this WatchlistinquirypostResponse.
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """
        Sets the reference_number of this WatchlistinquirypostResponse.
        Note: The ReferenceNumber is a unique value set by the invoker used to tie together service calls related to a single OFAC transaction between the invoker and the WLM API.

        :param reference_number: The reference_number of this WatchlistinquirypostResponse.
        :type: str
        """
        if reference_number is None:
            raise ValueError("Invalid value for `reference_number`, must not be `None`")

        self._reference_number = reference_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WatchlistinquirypostResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------