# coding: utf-8

"""
    Receive Side Callback API

    To facilitate the implementation of mVisa, Visa provides mVisa Receive Side API specifications to clients who implement a set of outbound RESTful APIs (Receive Side APIs) so that Visa can call these APIs to request clients to process the transactions over the Internet.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CashInpostResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, auth_id_response=None, response_code=None, receiver_transaction_id=None):
        """
        CashInpostResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'auth_id_response': 'str',
            'response_code': 'str',
            'receiver_transaction_id': 'str'
        }

        self.attribute_map = {
            'auth_id_response': 'authIdResponse',
            'response_code': 'responseCode',
            'receiver_transaction_id': 'receiverTransactionId'
        }

        self._auth_id_response = auth_id_response
        self._response_code = response_code
        self._receiver_transaction_id = receiver_transaction_id

    @property
    def auth_id_response(self):
        """
        Gets the auth_id_response of this CashInpostResponse.
        Contains the authorization code provided by the recipient when a transaction is approved. Visa recommends that recipient maintains uniqueness of this code for a given merchant PAN, however Visa would not maintain any checks for uniqueness. This field is to be sent as NULL if it is not populated.

        :return: The auth_id_response of this CashInpostResponse.
        :rtype: str
        """
        return self._auth_id_response

    @auth_id_response.setter
    def auth_id_response(self, auth_id_response):
        """
        Sets the auth_id_response of this CashInpostResponse.
        Contains the authorization code provided by the recipient when a transaction is approved. Visa recommends that recipient maintains uniqueness of this code for a given merchant PAN, however Visa would not maintain any checks for uniqueness. This field is to be sent as NULL if it is not populated.

        :param auth_id_response: The auth_id_response of this CashInpostResponse.
        :type: str
        """

        self._auth_id_response = auth_id_response

    @property
    def response_code(self):
        """
        Gets the response_code of this CashInpostResponse.
        Contains a code (also known as 'Action Code') that defines the response to a request. Refer to actionCode

        :return: The response_code of this CashInpostResponse.
        :rtype: str
        """
        return self._response_code

    @response_code.setter
    def response_code(self, response_code):
        """
        Sets the response_code of this CashInpostResponse.
        Contains a code (also known as 'Action Code') that defines the response to a request. Refer to actionCode

        :param response_code: The response_code of this CashInpostResponse.
        :type: str
        """
        if response_code is None:
            raise ValueError("Invalid value for `response_code`, must not be `None`")

        self._response_code = response_code

    @property
    def receiver_transaction_id(self):
        """
        Gets the receiver_transaction_id of this CashInpostResponse.
        Acquirer may provide a transaction ID that can be used for investigation if required. This field is to be sent as NULL if it is not populated

        :return: The receiver_transaction_id of this CashInpostResponse.
        :rtype: str
        """
        return self._receiver_transaction_id

    @receiver_transaction_id.setter
    def receiver_transaction_id(self, receiver_transaction_id):
        """
        Sets the receiver_transaction_id of this CashInpostResponse.
        Acquirer may provide a transaction ID that can be used for investigation if required. This field is to be sent as NULL if it is not populated

        :param receiver_transaction_id: The receiver_transaction_id of this CashInpostResponse.
        :type: str
        """

        self._receiver_transaction_id = receiver_transaction_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CashInpostResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------